
export const SIGNUP_FAILD = "SIGNUP_FAILD";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const LOGIN_FAILD = "LOGIN_FAILD";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAILD = "VERIFICATION_FAILD";

export const SET_VIEW = "SET_VIEW";
export const DEFAULT_VIEW = "DEFAULT_VIEW";
export const RESET_PASSWORD_VIEW = "RESET_PASSWORD_VIEW";
export const OTP_VERIFICATION_VIEW = "OTP_VERIFICATION_VIEW";

export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILD = "FORGET_PASSWORD_FAILD";

export const REQUEST_START = "REQUEST_START";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILD = "CHANGE_PASSWORD_FAILD";

export const CONFIRM_PASSWORD = "CONFIRM_PASSWORD";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
