
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_FAILD = "SIGNUP_FAILD";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const VERIFICATION_START = "VERIFICATION_START";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_FAILD = "VERIFICATION_FAILD";

export const SET_VIEW = "SET_VIEW";
export const DEFAULT_VIEW = "DEFAULT_VIEW";
export const EMAIL_VERIFICATION_VIEW = "EMAIL_VERIFICATION_VIEW";
