export const SET_GAMES_FORM = "SET_GAMES_FORM"
export const CHANGE_GAME_STATE = "CHANGE_GAME_STATE"
export const CREATE_GAMES_FAILED = "CREATE_GAMES_FAILED"
export const CREATE_GAMES_SUCCESS = "CREATE_GAMES_SUCCESS"

export const GETTING_GAMES_FAILED = "GETTING_GAMES_FAILED"
export const GETTING_GAMES_SUCCESS = "GETTING_GAMES_SUCCESS"
