export const CHANGE_MATCH_STATE = "CHANGE_MATCH_STATE"

export const CREATE_MATCH_FAILED = "CREATE_MATCH_FAILED"
export const CREATE_MATCH_SUCCESS = "CREATE_MATCH_SUCCESS"

export const GETTING_MATCH_FAILED = "GETTING_MATCH_FAILED"
export const GETTING_MATCH_SUCCESS = "GETTING_MATCH_SUCCESS"

export const UPDATING_MATCH_FAILED = "UPDATING_MATCH_FAILED"
export const UPDATING_MATCH_SUCCESS = "UPDATING_MATCH_SUCCESS"
