export const SET_PROFILE_FORM = "SET_PROFILE_FORM"
export const CREATE_FAN_PROFILE_FAILED = "CREATE_FAN_PROFILE_FAILED"
export const CREATE_FAN_PROFILE_SUCCESS = "CREATE_FAN_PROFILE_SUCCESS"

export const CREATE_TEAM_PROFILE_FAILED = "CREATE_TEAM_PROFILE_FAILED"
export const CREATE_TEAM_PROFILE_SUCCESS = "CREATE_TEAM_PROFILE_SUCCESS"
