export const SET_ROSTER_FORM = "SET_ROSTER_FORM"
export const CREATE_ROSTERS_FAILED = "CREATE_ROSTERS_FAILED"
export const CREATE_ROSTERS_SUCCESS = "CREATE_ROSTERS_SUCCESS"

export const GETTING_ROSTERS_FAILED = "GETTING_ROSTERS_FAILED"
export const GETTING_ROSTERS_SUCCESS = "GETTING_ROSTERS_SUCCESS"
